# -*- coding: utf-8 -*-
"""Copy of lokaverkefni vatnafræði.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1weV9AVA3D9odo-0LUDCy3TENbSeFKJVu

##**LOKAVEKREFNI VATNAFRÆÐI**

#*INNLESTUR GAGNA*
"""

import pandas as pd
import matplotlib.pyplot as plt

# Lesa gögn rennsli
fjollum_rennsli = pd.read_csv("ID_45_rennsli.csv",
                     sep=';',
                     parse_dates=[[0, 1, 2]],
                     usecols=[0, 1, 2, 3])

fjollum_rennsli.columns = ["date", "flow"]
mask_rennsli = (fjollum_rennsli['date'] >= '1993-10-01') & (fjollum_rennsli['date'] <= '2023-09-30')
fjollum_rennsli = fjollum_rennsli.loc[mask_rennsli]
fjollum_rennsli["water_year"] = fjollum_rennsli["date"].dt.year.where(fjollum_rennsli["date"].dt.month < 10,
                                                    fjollum_rennsli["date"].dt.year + 1)
fjollum_rennsli["month"] = fjollum_rennsli["date"].dt.month
monthly_rennsli = fjollum_rennsli.groupby("month")["flow"].mean()

# Lesa gögn úrkoma
fjollum_urkoma = pd.read_csv("ID_45_veður.csv",
                     sep=';',
                     parse_dates=[[0, 1, 2]],
                     usecols=[0, 1, 2, 29])

fjollum_urkoma.columns = ["date", "úrkoma"]
mask_urkoma = (fjollum_urkoma['date'] >= '1993-10-01') & (fjollum_urkoma['date'] <= '2023-09-30')
fjollum_urkoma = fjollum_urkoma.loc[mask_urkoma]
fjollum_urkoma["water_year"] = fjollum_urkoma["date"].dt.year.where(fjollum_urkoma["date"].dt.month < 10,
                                                    fjollum_urkoma["date"].dt.year + 1)
fjollum_urkoma["month"] = fjollum_urkoma["date"].dt.month
monthly_urkoma = fjollum_urkoma.groupby("month")["úrkoma"].mean()

# Lesa gögn hitastig
fjollum_hitastig = pd.read_csv("ID_45_veður.csv",
                     sep=';',
                     parse_dates=[[0, 1, 2]],
                     usecols=[0, 1, 2, 41])

fjollum_hitastig.columns = ["date", "hitastig"]
mask_hitastig = (fjollum_hitastig['date'] >= '1993-10-01') & (fjollum_hitastig['date'] <= '2023-09-30')
fjollum_hitastig = fjollum_hitastig.loc[mask_hitastig]
fjollum_hitastig["water_year"] = fjollum_hitastig["date"].dt.year.where(fjollum_hitastig["date"].dt.month < 10,
                                                    fjollum_hitastig["date"].dt.year + 1)
fjollum_hitastig["month"] = fjollum_hitastig["date"].dt.month
monthly_hitastig = fjollum_hitastig.groupby("month")["hitastig"].mean()

"""#LIÐUR 2

"""

#teikna meðal ársrennsli
months = range(1,13)
month_labels = ['Jan', 'Feb', 'Mar', 'Apr', 'Maí', 'Jún', 'Júl', 'Ágú', 'Sep', 'Okt', 'Nóv', 'Des']
fig, ax = plt.subplots(figsize=(10, 3))
plt.plot(monthly_rennsli.index, monthly_rennsli.values, color='navy', linewidth=2, label="Jökulsá á Fjöllum")
plt.xlabel("Mánuður")
plt.ylabel("Meðalrennsli (m³/s)")
plt.xticks(months,month_labels)
plt.legend()
plt.title("Meðal mánaðar rennsli (1993-2023)")
plt.grid(True)
plt.show()

#teikna meðal ársúrkomu
months = range(1,13)
month_labels = ['Jan', 'Feb', 'Mar', 'Apr', 'Maí', 'Jún', 'Júl', 'Ágú', 'Sep', 'Okt', 'Nóv', 'Des']
fig, ax = plt.subplots(figsize=(10, 3))
plt.plot(monthly_urkoma.index, monthly_urkoma.values, color='skyblue', linewidth=2, label="Jökulsá á Fjöllum")
plt.xlabel("Mánuður")
plt.ylabel("Meðalúrkoma á dag (mm/d)")
plt.xticks(months,month_labels)
plt.legend()
plt.title("Meðal mánaðar úrkoma (1993-2023)")
plt.grid(True)
plt.show()

#teikna meðal árshitastig
months = range(1,13)
month_labels = ['Jan', 'Feb', 'Mar', 'Apr', 'Maí', 'Jún', 'Júl', 'Ágú', 'Sep', 'Okt', 'Nóv', 'Des']
fig, ax = plt.subplots(figsize=(10, 3))
plt.plot(monthly_hitastig.index, monthly_hitastig.values, color='orangered', linewidth=2, label="Jökulsá á Fjöllum")
plt.xlabel("Mánuður")
plt.ylabel("Meðalhitastig (C)")
plt.xticks(months,month_labels)
plt.legend()
plt.title("Meðal mánaðar hitastig (1993-2023)")
plt.grid(True)
plt.show()

"""# *LIÐUR 3*"""

import numpy as np
import matplotlib.pyplot as plt

def baseflow_filter(Q, alpha=0.925, passes=3):
    """Ladson et al. (2013) útfærsla á Lyne & Hollick síu."""
    q_f = np.zeros(len(Q))
    q_b = np.copy(Q)

    for _ in range(passes):
        for i in range(1, len(Q)):
            # Lyne & Hollick jafna
            q_f[i] = alpha * q_f[i-1] + (1 + alpha)/2 * (Q[i] - Q[i-1])
            q_f[i] = max(0, q_f[i]) # Quickflow má ekki vera neikvætt

        q_b = Q - q_f
        # Passa að grunnrennsli fari ekki yfir heildarrennsli
        q_b = np.where(q_b < 0, 0, q_b)
        q_b = np.where(q_b > Q, Q, q_b)
        Q = q_b # Fyrir næsta "pass"

    return q_b

fjollum_rennsli['baseflow'] = baseflow_filter(fjollum_rennsli['flow'].values)

bfi = fjollum_rennsli['baseflow'].sum() / fjollum_rennsli['flow'].sum()
print(f"Baseflow Index (BFI): {bfi:.2f}")

#teiknum mynd
mask = (fjollum_rennsli['date'] >= '2022-10-01') & (fjollum_rennsli['date'] <= '2023-09-30')
plot_data = fjollum_rennsli.loc[mask].copy()
plot_data['quickflow'] = plot_data['flow'] - plot_data['baseflow']

fig, ax = plt.subplots(figsize=(10, 4))
#grunnrennsli
plt.fill_between(plot_data['date'], plot_data['baseflow'], color='hotpink', alpha=0.5, label='Grunnrennsli')
#heildarrennsi
plt.fill_between(plot_data['date'], plot_data['baseflow'], plot_data['flow'], color='blue', alpha=0.5, label='Yfirborðsrennsli')
#heildarrennsi
plt.plot(plot_data['date'], plot_data['flow'], color='black', linewidth=0.8, alpha=0.7)
plt.title(f"Grunn- og heildarrennsli Jökulsár á Fjöllum -vatnsár 2023", fontsize=14)
plt.ylabel("Rennsli (m³/s)")
plt.xlabel("Dagsetning")
plt.legend(loc='upper right')
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

upphafs_dags = '2022-12-24' #upphafs dags
loka_dags = '2023-02-04'#loka dagsettning
sample = fjollum_rennsli.set_index('date').loc[upphafs_dags:loka_dags].copy()
t = np.arange(len(sample))
y = np.log(sample['flow'].values)

#finnum bestu línu
halli, intercept = np.polyfit(t, y, 1)
k = -1 / halli

print(f"Tímabil: {upphafs_dags} til {loka_dags}")
print(f"Hallatala: {halli:.4f}")
print(f"Recession constant (k): {k:.1f} dagar")

#Teiknum mynd
Q0 = sample['flow'].iloc[0]
fitted_Q = Q0 * np.exp(-t / k)

plt.figure(figsize=(10, 4))
plt.plot(sample.index, sample['flow'], 'o-', label='Mælt rennsli', color='hotpink')
plt.plot(sample.index, fitted_Q, '--', label=f'Líkan (k={k:.1f} d)', color='mediumpurple', linewidth=2)

plt.title(f"Rennsli Jökulsár á Fjöllum ({upphafs_dags} - {loka_dags})")
plt.xlabel("Dagsetning")
plt.ylabel("Rennsli (m³/s)")
plt.legend()
plt.grid(True, linestyle=':', alpha=0.6)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""##

#LIÐUR 4
"""

import pandas as pd
import matplotlib.pyplot as plt

days = [31,28,31,30,31,30,31,31,30,31,30,31]
# Rennsli
#Flatarmál vatnasviðsins er 5150,848 km^2 úr frá töflu, breytum því í m^2
area_calc = 5150.848 * 1e6
fjollum_rennsli = pd.read_csv("ID_45_rennsli.csv",
                     sep=';',
                     parse_dates=[[0, 1, 2]],
                     usecols=[0, 1, 2, 3])

fjollum_rennsli.columns = ["date", "flow"]
mask_rennsli = (fjollum_rennsli['date'] >= '1993-10-01') & (fjollum_rennsli['date'] <= '2023-09-30')
fjollum_rennsli = fjollum_rennsli.loc[mask_rennsli]
fjollum_rennsli["water_year"] = fjollum_rennsli["date"].dt.year.where(fjollum_rennsli["date"].dt.month < 10,
                                                    fjollum_rennsli["date"].dt.year + 1)
fjollum_rennsli["month"] = fjollum_rennsli["date"].dt.month
monthly_rennsli = fjollum_rennsli.groupby("month")["flow"].mean()

# Úrkoma

fjollum_urkoma = pd.read_csv("ID_45_veður.csv",
                     sep=';',
                     parse_dates=[[0, 1, 2]],
                     usecols=[0, 1, 2, 29])

fjollum_urkoma.columns = ["date", "úrkoma"]
mask_urkoma = (fjollum_urkoma['date'] >= '1993-10-01') & (fjollum_urkoma['date'] <= '2023-09-30')
fjollum_urkoma = fjollum_urkoma.loc[mask_urkoma]
fjollum_urkoma["water_year"] = fjollum_urkoma["date"].dt.year.where(fjollum_urkoma["date"].dt.month < 10,
                                                    fjollum_urkoma["date"].dt.year + 1)
fjollum_urkoma["month"] = fjollum_urkoma["date"].dt.month
monthly_urkoma = fjollum_urkoma.groupby("month")["úrkoma"].mean()

# Uppgufun

fjollum_uppgufun = pd.read_csv("ID_45_veður.csv",
                               sep=';',
                               parse_dates=[[0,1,2]],
                               usecols=[0,1,2,56])
fjollum_uppgufun.columns = ["date","uppgufun"]
mask_uppgufun = (fjollum_uppgufun['date'] >= '1993-10-01') & (fjollum_uppgufun['date'] <= '2023-09-30')
fjollum_uppgufun = fjollum_uppgufun.loc[mask_uppgufun]
fjollum_uppgufun["water_year"] = fjollum_uppgufun["date"].dt.year.where(fjollum_uppgufun["date"].dt.month < 10,
                                                    fjollum_uppgufun["date"].dt.year + 1)
fjollum_uppgufun["month"] = fjollum_uppgufun["date"].dt.month
monthly_uppgufun = fjollum_uppgufun.groupby("month")["uppgufun"].mean()

# Mánaðar gögn
monthly_rennsli = monthly_rennsli.reset_index()
monthly_rennsli.columns = ["month", "Q_m3s"]

monthly_urkoma = monthly_urkoma.reset_index()
monthly_urkoma.columns = ["month", "P_mmdag"]

monthly_uppgufun = monthly_uppgufun.reset_index()
monthly_uppgufun.columns = ["month", "ET_mmdag"]

# Sameina í eina töflu
tafla = monthly_rennsli.merge(monthly_urkoma, on="month")
tafla = tafla.merge(monthly_uppgufun, on="month")

# Bæta við fjölda daga í mánuði
tafla["days"] = days

# Breyta P og ET úr mm/dag í mm/mánuð
tafla["P_mmmán"] = tafla["P_mmdag"] * tafla["days"]
tafla["ET_mmmán"] = tafla["ET_mmdag"] * tafla["days"]

# Breyta Q úr m3/s í mm/mánuð
tafla["Q_mmmán"] = (tafla["Q_m3s"] * 86400 * tafla["days"] / area_calc) * 1000

# Reikna breytingu í geymslu
tafla["dS_mmmán"] = tafla["P_mmmán"] - tafla["Q_mmmán"] - tafla["ET_mmmán"]

# Setja mánuðarnöfn
month_names = ["Jan", "Feb", "Mar", "Apr", "Maí", "Jún",
               "Júl", "Ágú", "Sep", "Okt", "Nóv", "Des"]
tafla["mánuður"] = month_names

# Prenta töflu
print(tafla[["mánuður", "Q_mmmán", "P_mmmán", "ET_mmmán", "dS_mmmán"]].round(2))

# Graf fyrir breytingu í geymslu
plt.figure(figsize=(8,4))
plt.bar(tafla["mánuður"], tafla["dS_mmmán"])
plt.axhline(0, color='black', linewidth=1)
plt.xlabel("Mánuður")
plt.ylabel("ΔS (mm/mánuð)")
plt.title("Breyting á geymslu yfir árið (ΔS)")
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""#LIÐUR 5"""

import numpy as np
import matplotlib.pyplot as plt

#stærðar raða gögnum
data = fjollum_rennsli['flow'].dropna().sort_values(ascending=False).values
n = len(data)

#líkur reiknaðar með: P = 100 * (rank / (n + 1))
prob = 100 * (np.arange(1, n + 1) / (n + 1))

#Q5, Q50 og Q95
q5 = np.percentile(data, 95)
q50 = np.percentile(data, 50)
q95 = np.percentile(data, 5)

print(f"Q5 (Hárennsli): {q5:.2f} m³/s")
print(f"Q50 (Miðgildi): {q50:.2f} m³/s")
print(f"Q95 (Lágrennsli): {q95:.2f} m³/s")

#Teikna
plt.figure(figsize=(10, 4))
plt.plot(prob, data, color='hotpink', linewidth=2)

for q, p, label in zip([q5, q50, q95], [5, 50, 95], ['Q5', 'Q50', 'Q95']):
    plt.axvline(p, color='mediumpurple', linestyle=':', alpha=0.5)
    plt.text(p+1, q+10, f"{label}: {q:.1f}", color='mediumpurple', fontweight='bold')

plt.yscale('log') # Oft gott að hafa log-ás til að sjá lágrennslið betur
plt.title("Langæislína Jökulsá á Fjöllum")
plt.xlabel("Hlutfall tíma þar sem rennsli er farið fram úr [%]")
plt.ylabel("Rennsli [m³/s] - lógaritmískur kvarði")
plt.grid(True, which="both", ls="-", alpha=0.3)
plt.show()

"""#LIÐUR 6"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


def annual_peak_month(df):

    idx = df.groupby("water_year")["flow"].idxmax()
    peaks = df.loc[idx, ["water_year", "date", "flow"]].copy()
    peaks["month"] = peaks["date"].dt.month
    return peaks.sort_values("water_year")

rennsli_peaks = annual_peak_month(fjollum_rennsli)

rennsli_counts = rennsli_peaks["month"].value_counts().sort_index()

months = np.arange(1, 13)
rennsli_vals = np.array([rennsli_counts.get(m, 0) for m in months])

months = range(1,13)
month_labels = ['Jan', 'Feb', 'Mar', 'Apr', 'Maí', 'Jún', 'Júl', 'Ágú', 'Sep', 'Okt', 'Nóv', 'Des']
fig, ax = plt.subplots(figsize=(10, 3))
ax.bar(months, rennsli_vals, color='pink')
ax.set_title("Árstíðardreifing flóða: mánuður með mesta flóð á ári (1993-2023)")
ax.set_xlabel("Mánuður")
ax.set_ylabel("Fjöldi árstoppflóða")
ax.legend(["Jökulsá á Fjöllum"])
ax.set_xticks(months)
ax.set_xticklabels(month_labels)
plt.tight_layout()
plt.grid(True)
plt.show()

# 5 stærstu flóðin með dagsetningum fyrir lið 8
rennsli_peaks.sort_values("flow", ascending=False).head(5)

from scipy.stats import gumbel_r, lognorm, pearson3
import numpy as np

peak_flows = rennsli_peaks["flow"].values
peak_flows = np.sort(peak_flows)[::-1]

n = len(peak_flows)
m = np.arange(1,n+1)

p_exceed = (m-0.44)/(n+0.12)
T = 1/p_exceed

#Gumbel
params_gumbel = gumbel_r.fit(peak_flows)

#Log Normal 3
params_lognormal = lognorm.fit(peak_flows)

#Log Pearson 3
log_flows = np.log10(peak_flows)
params_lp3 = pearson3.fit(log_flows)

#Hvað er best?
F = 1 - p_exceed

q_gumbel = gumbel_r.ppf(F, *params_gumbel)
q_lognorm = lognorm.ppf(F, *params_lognormal)
q_lp3 = 10 ** pearson3.ppf(F, *params_lp3)

# SSE
sse_gumbel = np.sum((peak_flows - q_gumbel)**2)
sse_lognorm = np.sum((peak_flows - q_lognorm)**2)
sse_lp3 = np.sum((peak_flows - q_lp3)**2)


#Reiknum svo Q10, Q50 og Q100
T_vals = np.array([10, 50, 100])
F_vals = 1 - 1 / T_vals

Q_gumbel = gumbel_r.ppf(F_vals, *params_gumbel)
Q_lognorm = lognorm.ppf(F_vals, *params_lognormal)
Q_lp3 = 10 ** pearson3.ppf(F_vals, *params_lp3)

rng = np.random.default_rng(42)
n_boot = 1000

boot_q10 = []
boot_q50 = []
boot_q100 = []

for _ in range(n_boot):
    sample = rng.choice(peak_flows, size=len(peak_flows), replace=True)

    if sse_gumbel < sse_lognorm and sse_gumbel < sse_lp3:
        params = gumbel_r.fit(sample)
        q = gumbel_r.ppf(F_vals, *params)

    elif sse_lognorm < sse_lp3:
        params = lognorm.fit(sample)
        q = lognorm.ppf(F_vals, *params)

    else:
        sample_log = np.log10(sample)
        params = pearson3.fit(sample_log)
        q = 10 ** pearson3.ppf(F_vals, *params)

    boot_q10.append(q[0])
    boot_q50.append(q[1])
    boot_q100.append(q[2])

print("Gumbel:", sse_gumbel)
print("LogNormal3:", sse_lognorm)
print("LogPearson3:", sse_lp3)

print("Q_gumbel:", Q_gumbel)
print("Q_lognorm:", Q_lognorm)
print("Q_lp3:", Q_lp3)

print("Q10 CI:", np.percentile(boot_q10, [5, 95]))
print("Q50 CI:", np.percentile(boot_q50, [5, 95]))
print("Q100 CI:", np.percentile(boot_q100, [5, 95]))

import matplotlib.pyplot as plt

T_plot = np.linspace(1.1, 200, 500)
F_plot = 1 - 1 / T_plot

plt.figure(figsize=(8,5))
plt.scatter(T, peak_flows, label="Mæld annual peaks")

plt.plot(T_plot, gumbel_r.ppf(F_plot, *params_gumbel), label="Gumbel")
plt.plot(T_plot, lognorm.ppf(F_plot, *params_lognormal), label="Log Normal 3")
plt.plot(T_plot, 10**pearson3.ppf(F_plot, *params_lp3), label="Log Pearson 3")

plt.xscale("log")
plt.xlabel("Endurkomutími (ár)")
plt.ylabel("Rennsli (m³/s)")
plt.title("Flóðagreining")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

"""# LIÐUR 7"""

!pip install pymannkendall
import pymannkendall as mk
import pandas as pd

#meðalrennsli ára
annual_flow = fjollum_rennsli.groupby(fjollum_rennsli['date'].dt.year)['flow'].mean()

#greining
def analyze_trend(data, label):
    res = mk.hamed_rao_modification_test(data)

    # Niðurstöður
    print(f"--- {label} ---")
    print(f"Leitni: {res.trend}")
    print(f"p-gildi: {res.p:.4f}")
    print(f"Sen's Slope: {res.slope:.4f} (m³/s á ári)")
    print(f"Marktækt (p < 0.05): {res.p < 0.05}")
    print("-" * 20)

#allt árið í heild
analyze_trend(annual_flow, "Árið í heild")

#árstíðit
seasons = {
    "Vetur (nóv-mars)": [11, 12, 1, 2, 3],
    "Vor (apr-maí)": [4, 5, 6],
    "Sumar (júl-ágúst)": [7, 8],
    "Haust (sept-okt)": [9, 10]
}
#farið í gegnum allar árstiðir
for nafn, man in seasons.items():
    seasonal_data = fjollum_rennsli[fjollum_rennsli['date'].dt.month.isin(man)]
    seasonal_avg = seasonal_data.groupby(seasonal_data['date'].dt.year)['flow'].mean()
    #greining
    if not seasonal_avg.empty:
        analyze_trend(seasonal_avg, nafn)

#mánuðir
manudir = {
    "janúar": [1],
    "febrúar": [2],
    "mars": [3],
    "apríl": [4],
    "maí": [5],
    "júní": [6],
    "júlí": [7],
    "ágúst": [8],
    "september": [9],
    "október": [10],
    "nóvember": [11],
    "desember": [12],
}

#farið í gegnum alla mánuði
for nafn, man in manudir.items():
    manadar_data = fjollum_rennsli[fjollum_rennsli['date'].dt.month.isin(man)]
    manadar_avg = manadar_data.groupby(manadar_data['date'].dt.year)['flow'].mean()
    #greining
    if not manadar_avg.empty:
        analyze_trend(manadar_avg, nafn)

"""#LIÐUR 8"""

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

event_date = pd.to_datetime("2004-08-15")

start = event_date - pd.Timedelta(days=10)
end = event_date + pd.Timedelta(days=10)


event_Q = fjollum_rennsli[(fjollum_rennsli["date"] >= start) & (fjollum_rennsli["date"] <= end)]

event_P = fjollum_urkoma[(fjollum_urkoma["date"] >= start) & (fjollum_urkoma["date"] <= end)]

event_T = fjollum_hitastig[(fjollum_hitastig["date"] >= start) & (fjollum_hitastig["date"] <= end)]

# Dagsetningar
q_start = pd.to_datetime("2004-08-08")
q_peak = pd.to_datetime("2004-08-15")
q_recession_end = pd.to_datetime("2004-08-21")

rain_release_start = pd.to_datetime("2004-08-08")
rain_release_end = pd.to_datetime("2004-08-21")

heat_release_start = pd.to_datetime("2004-08-20")
heat_release_end = pd.to_datetime("2004-08-21")

# Reikna daga
time_to_peak_days = (q_peak - q_start).days
recession_days = (q_recession_end - q_peak).days
excess_rain_days = (rain_release_end - rain_release_start).days
excess_heat_days = (heat_release_end - heat_release_start).days

# Mynd
fig, ax1 = plt.subplots(figsize=(10,5))

# Rennsli
ax1.plot(event_Q["date"], event_Q["flow"], color="navy", linewidth=2)
ax1.set_ylabel("Rennsli (m³/s)", color="navy")
ax1.tick_params(axis='y', labelcolor="navy")
ax1.set_xlabel("Dagsetning")

# Hægri ás fyrir hitastig og úrkomu
ax2 = ax1.twinx()

# Hitastig
ax2.plot(event_T["date"], event_T["hitastig"], color="red", linewidth=2)

# Úrkoma
ax2.bar(event_P["date"], event_P["úrkoma"], width=0.8, alpha=0.35, color="blue")

ax2.set_ylabel("Hitastig (°C) og Úrkoma (mm)")

# Lóðréttar línur
ax1.axvline(q_start, color='black', linestyle='--', linewidth=1.2, alpha=0.8)
ax1.axvline(q_peak, color='black', linestyle='--', linewidth=1.8)
ax1.axvline(q_recession_end, color='black', linestyle='--', linewidth=1.2, alpha=0.8)

# Texti fyrir Qmax
ax1.text(q_peak + pd.Timedelta(days=0.2), ax1.get_ylim()[1]*0.97, "Qmax", fontsize=12, color="black", va="top")

# Hæðir fyrir örvar
y1 = event_Q["flow"].min() + 150
y2 = event_Q["flow"].min() + 90
y3 = event_Q["flow"].min() + 20
y4 = event_Q["flow"].min() + 90

# Time-to-peak
ax1.annotate( "", xy=(q_peak, y4), xytext=(q_start, y4), arrowprops=dict(arrowstyle="<->", color="darkgoldenrod", lw=2))
ax1.text(q_start + (q_peak - q_start)/2, y4 + 10, f"Time-to-peak\n({time_to_peak_days} dagar)", color="darkgoldenrod", ha="center", va="bottom", fontsize=12)

# Excess rain release time
ax1.annotate( "", xy=(rain_release_end, y3), xytext=(rain_release_start, y3), arrowprops=dict(arrowstyle="<->", color="forestgreen", lw=2))
ax1.text( rain_release_start + (rain_release_end - rain_release_start)/2, y3 + 10, f"Excess rain release time\n({excess_rain_days} dagar)", color="forestgreen", ha="center", va="bottom", fontsize=11)

# Excess heat release time
ax1.annotate( "", xy=(heat_release_end, y2), xytext=(heat_release_start, y2), arrowprops=dict(arrowstyle="<->", color="olivedrab", lw=2))
ax1.text( heat_release_start + (heat_release_end - heat_release_start)/2, y2 + 10, f"Excess heat release time\n({excess_heat_days} dagur)", color="olivedrab", ha="center", va="bottom", fontsize=11)

# Recession time
ax1.annotate( "", xy=(q_recession_end, y1), xytext=(q_peak, y1), arrowprops=dict(arrowstyle="<->", color="purple", lw=2))
ax1.text( q_peak + (q_recession_end - q_peak)/2, y1 + 10, f"Recession time\n({recession_days} dagar)", color="purple", ha="center", va="bottom", fontsize=12)

# Legend
legend_elements = [ Line2D([0], [0], color='navy', lw=2, label='Rennsli (Q)'), Line2D([0], [0], color='red', lw=2, label='Hitastig (T)'), Patch(facecolor='blue', edgecolor='blue', alpha=0.35, label='Úrkoma (P)')]
ax1.legend(handles=legend_elements, loc="upper left", frameon=True)

plt.title("Rennslisatburður 15. ágúst 2004")
fig.autofmt_xdate()
plt.tight_layout()
plt.show()
